[go] fix correctness check in env.py to work with symlinks.
I use a lot of symlinks for faster navigation in our codebase,
which unfortunately results in assertions like this:

  Traceback (most recent call last):
    File "/ii/infra/go/env.py", line 32, in <module>
      raise AssertionError(
  AssertionError: Imported wrong bootstrap.py
    /home/tandrii/s/ii/infra/go/bootstrap.py instead of
    /ii/infra/go/bootstrap.py

R=vadimsh

Change-Id: Id0a257376a38c782dd162809fb12b9bad3d942d6
Reviewed-on: https://chromium-review.googlesource.com/c/infra/infra/+/2940173
Auto-Submit: Andrii Shyshkalov <tandrii@google.com>
Commit-Queue: Vadim Shtayura <vadimsh@chromium.org>
Reviewed-by: Vadim Shtayura <vadimsh@chromium.org>
Cr-Commit-Position: refs/heads/master@{#41459}