Revert "[go] update deps"
This reverts commit 81d72181fba691a21bbe448ab03dabcdd79c049a.

Reason for revert: broke lucicfg (starlark).
    --- FAIL: TestAllStarlark/testdata/errors/bad_builder_props.star (0.05s)
        starlark_test.go:164: Got:
            
            Traceback (most recent call last):
              //testdata/errors/bad_builder_props.star: in <toplevel>
              <builtin>: in _builder
            Error in to_json: to_json: unsupported type struct
            
            Was expecting pattern:
            
            Traceback (most recent call last):
              //testdata/errors/bad_builder_props.star: in <toplevel>
              ...
            Error: to_json: unsupported type struct
            
        starlark_test.go:164: Regexp: ^Traceback \(most recent call last\):\n  //testdata/errors/bad_builder_props\.star: in <toplevel>\n(.*\n)*Error: to_json: unsupported type struct\n$
See more in https://logs.chromium.org/logs/infra/buildbucket/cr-buildbucket.appspot.com/8862649318073425280/+/u/go_test/stdout

Original change's description:
> [go] update deps
>
> I added golang.org/x/term for
> https://go.googlesource.com/crypto.git/+/4be66e5b658251a93e17d931a68d9c0ecba9f83a
>
> Also skip a broken test.
>
> --------------------------------------------------------------------------
> Dependencies added to deps.lock:
> * golang.org/x/term
> --------------------------------------------------------------------------
> --------------------------------------------------------------------------
> Updated repos:
> https://code.googlesource.com/gocloud.git/+log/b4d5e15a4a5b..f37f118c87d4
> https://chromium.googlesource.com/external/github.com/antlr/antlr4.git/+log/ac92c48a09df..86610fd4b43e
> https://chromium.googlesource.com/external/github.com/disintegration/imaging.git/+log/879073f2332f..9edfa1ec221b
> https://chromium.googlesource.com/external/github.com/emirpasic/gods.git/+log/7e2349589531..79df803e554c
> https://chromium.googlesource.com/external/github.com/go-ole/go-ole.git/+log/14974a1cf647..d467d8080fc3
> https://chromium.googlesource.com/external/github.com/go-sql-driver/mysql.git/+log/84241ad3f472..cf72fd249522
> https://chromium.googlesource.com/external/github.com/gomodule/redigo.git/+log/bd964e5f79dd..c4a82d62aa08
> https://chromium.googlesource.com/external/github.com/google/go-cmp.git/+log/d2fcc899bdc2..ec71d6d79053
> https://chromium.googlesource.com/external/github.com/google/pprof.git/+log/20978b51388d..ae444373da19
> https://chromium.googlesource.com/external/github.com/jmoiron/sqlx.git/+log/0794cb1f47ee..00c6e74d816a
> https://chromium.googlesource.com/external/github.com/klauspost/compress.git/+log/3d6de88355cc..ff4a4acf3be7
> https://chromium.googlesource.com/external/github.com/mattn/go-tty.git/+log/acb06aaba0f8..72ed86c4554d
> https://chromium.googlesource.com/external/github.com/microsoft/go-winio.git/+log/5b44b70ab3ab..f314918fc79c
> https://chromium.googlesource.com/external/github.com/pelletier/go-buffruneio.git/+log/25c428535bd3..fc38418f1eae
> https://chromium.googlesource.com/external/github.com/pkg/sftp.git/+log/4bca1e2f41ac..7230c61342c8
> https://chromium.googlesource.com/external/github.com/protocolbuffers/txtpbfmt.git/+log/ebd45c707ce7..f6a6b3f636fc
> https://chromium.googlesource.com/external/github.com/google/starlark-go.git/+log/dff0ae5b4820..e55f603d8c79
> https://go.googlesource.com/build.git/+log/d72655cc593d..2e05377d7423
> https://go.googlesource.com/crypto.git/+log/9e8e0b390897..c8d3bf9c5392
> https://go.googlesource.com/mod.git/+log/ce943fd02449..3bfbaada29be
> https://go.googlesource.com/sys.git/+log/215b40eba54c..f84b799fce68
> https://go.googlesource.com/text.git/+log/22f1617af38e..967b8f6126b0
> https://go.googlesource.com/tools.git/+log/169ad6d6ecb2..299f270db459
> https://chromium.googlesource.com/external/github.com/googleapis/go-genproto.git/+log/2640f1f9cdfb..9b1e624d6bc4
> https://chromium.googlesource.com/external/github.com/grpc/grpc-go.git/+log/aeb04798c556..44e408dab41e
> https://chromium.googlesource.com/external/github.com/go-yaml/yaml.git/+log/b893565b90ca..7649d4548cb5
> --------------------------------------------------------------------------
>
> Bug: 1152663, 1152683
> Change-Id: Ic401628b298bd2d58ce8c57a13c3926e2b40fd23
> Reviewed-on: https://chromium-review.googlesource.com/c/infra/infra/+/2559753
> Commit-Queue: Andrii Shyshkalov <tandrii@google.com>
> Reviewed-by: Andrii Shyshkalov <tandrii@google.com>
> Auto-Submit: Takuto Ikuta <tikuta@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#36704}

TBR=tandrii@google.com,tikuta@chromium.org,infra-scoped@luci-project-accounts.iam.gserviceaccount.com,sokcevic@google.com

Change-Id: I386f0b2eb2e1c94e7f4b57a767d1c4698f5e13f7
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 1152663
Bug: 1152683
Reviewed-on: https://chromium-review.googlesource.com/c/infra/infra/+/2561058
Reviewed-by: Andrii Shyshkalov <tandrii@google.com>
Commit-Queue: Andrii Shyshkalov <tandrii@google.com>
Cr-Commit-Position: refs/heads/master@{#36705}