[buildbucket] build_id in handler is string, not int.
Fix bug that happened in production:

  ...
  File "third_party/webapp2-2.5.2/webapp2.py", line 570, in dispatch
    return method(*args, **kwargs)
  File "handlers.py", line 127, in get
    (log_name, step_name, build_id)
  TypeError: %d format: a number is required, not str

R=yuanjunh

Change-Id: Iaa263012c0352e501269dc9a0206753f73b72b8b
Reviewed-on: https://chromium-review.googlesource.com/c/infra/infra/+/2669588
Auto-Submit: Andrii Shyshkalov <tandrii@google.com>
Commit-Queue: Yuanjun Huang <yuanjunh@google.com>
Reviewed-by: Yuanjun Huang <yuanjunh@google.com>
Cr-Commit-Position: refs/heads/master@{#38174}