chromium-build-stats: update trace-viewer.html
trace-viewer.html doesn't work on recent chrome, due to
 Uncaught TypeError: document.registerElement is not a function

generate new trace-viewer.html with
 'catapult_revision': 'ea794b87a8c5a2439c21bfc38e36e74aa8c2c518'

need to specify trial origin tokens for
https://chromium-build-stats.appspot.com and
https://chromium-build-stats-staging.appspot.com
registered on https://developers.chrome.com/origintrials/#/trials/active
for WebComponents V0.

Those trial origin tokens will be expired on Feb 2, 2021.

Bug: 1050215
Change-Id: I8e2af6f2b8f90c0df87ca91d887041e7a0b2007e
Reviewed-on: https://chromium-review.googlesource.com/c/infra/infra/+/2044041
Reviewed-by: Takuto Ikuta <tikuta@chromium.org>
Commit-Queue: Fumitoshi Ukai <ukai@chromium.org>
Cr-Commit-Position: refs/heads/master@{#28984}