python_ssl_suffix: Look at /etc/pki/tls as well.
This directory is used by Fedora, RHEL and derived distros instead of
/etc/ssl.

This prevents errors such as

  File "/data/src/depot_tools/bootstrap-3.8.0b1.chromium.1_bin/python/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/data/src/depot_tools/bootstrap-3.8.0b1.chromium.1_bin/python/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/data/src/depot_tools/bootstrap-3.8.0b1.chromium.1_bin/python/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/data/src/depot_tools/bootstrap-3.8.0b1.chromium.1_bin/python/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/data/src/depot_tools/bootstrap-3.8.0b1.chromium.1_bin/python/lib/python2.7/urllib2.py", line 1241, in https_open
    context=self._context)
  File "/data/src/depot_tools/bootstrap-3.8.0b1.chromium.1_bin/python/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
  urllib2.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:726)>

when running 'src/tools/clang/scripts/update.py' as part of 'gclient
runhooks' in one of those distros.

Tentatively referencing bug 967136 as I do not have access to it, but it was
brought up on Slack when this issue was mentioned.

Bug: 967136
Change-Id: I34e77de6a1ed3761fc2c7f4765916c6756ea85fe
Reviewed-on: https://chromium-review.googlesource.com/c/infra/infra/+/1929031
Reviewed-by: Ben Pastene <bpastene@chromium.org>
Reviewed-by: Robbie Iannucci <iannucci@chromium.org>
Commit-Queue: Raphael Kubo da Costa <raphael.kubo.da.costa@intel.com>
Auto-Submit: Raphael Kubo da Costa <raphael.kubo.da.costa@intel.com>
Cr-Commit-Position: refs/heads/master@{#27226}